api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from .views import *
from .viewsets import ContratosViewSet, TipocontratoViewSet

router = routers.SimpleRouter()
router.register(r'contratos', ContratosViewSet, TipocontratoViewSet)


urlpatterns = [
    path('v1/contratos/',ContratosList.as_view(),name='contratos_list'),
    path('v1/contratos/<str:id>',ContratosDetalle.as_view(),name='contratos_detalle'),
    path('v1/tipocontrato/<str:id>',TipocontratoDetalle.as_view(),name='tipocontrato_detalle'),
    path('',include(router.urls)),
    path('token/', TokenObtainPairView.as_view(), name = 'token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name = 'token_refresh'),
]

contrato/urls.py
import debug_toolbar
from django.views.static import serve
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
#from cto import views





urlpatterns = [

    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('cto/', include(('cto.urls', 'cto'), namespace='cto')),
    path('ley/', include(('ley.urls', 'ley'), namespace='ley')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    
  
    
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),

    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),


    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

if settings.DEBUG:
    
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

cto/urls.py
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static
#from .reportes import imprimir_solicitud, imprimir_archivos


urlpatterns = [

    path('contratos/contrata/<int:id>',
         coverletter_export, name="coverletter_export"),

    path('contratos/avanza/<int:id>', contratosAvanza, name="contratos_avanza"),
    path('contratos/devuelve/<int:id>',
         contratosDevuelve, name="contratos_devuelve"),


    path('coverletter/export', coverletter_export, name='coverletter_export'),

    path('departamentos/', DepartamentoView.as_view(), name="departamento_list"),
    path('departamentos/new', DepartamentoNew.as_view(), name="departamento_new"),
    path('departamentos/<int:pk>', DepartamentoEdit.as_view(),
         name="departamento_edit"),
    path('departamentos/estado/<int:id>',
         departamentoInactivar, name="departamento_inactivar"),


    path('puestos/', PuestosView.as_view(), name="puestos_list"),
    path('puestos/new', PuestosNew.as_view(), name="puestos_new"),
    path('puestos/<int:pk>', PuestosEdit.as_view(), name="puestos_edit"),
    # path('partes/estado/<int:id>',partesInactivar, name="partes_inactivar"),
    path('puestos/buscar-parte', PuestosView.as_view(), name="buscar_puesto"),




    path('partes/', PartesView.as_view(), name="partes_list"),
    path('partes/new', PartesNew.as_view(), name="partes_new"),
    path('partes/<int:pk>', PartesEdit.as_view(), name="partes_edit"),
    path('partes/estado/<int:id>', partesInactivar, name="partes_inactivar"),
    path('partes/buscar-parte', PartesView.as_view(), name="buscar_parte"),




    path('contratos/', ContratosView.as_view(), name="contrato_list"),
    path('contratos/new', contratos2, name="contrato_new"),
    path('contratos/edit/<int:contrato_id>', contratos2, name="contrato_edit"),
    path('contratos/edit2/<int:pk>',
         ContratosEdit.as_view(), name="contrato_edit2"),

    #path('partes/new2',partes2, name="sujeto_new"),
    path('contratos/gracont/<int:id>', contratoGracont, name="contrato_gracont"),

    path('doctos/<int:contrato_id>/delete/<int:pk>',
         DoctosDetDelete.as_view(), name="doctos_del"),
    path('doctos/edit/<int:contrato_id>', contratos2, name="doctos_edit"),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

cto/views.py
#from json.decoder import JSONDecoder
#from typing import Any, Dict
from django.conf.urls import url
from django.urls.conf import path
import docx
import locale
import json
import requests
import urllib
from urllib import request, parse


import io
from operator import index
from pathlib import Path
import os


# Para utilizar algunas de las funciones de la librería
from docx import Document
from docx.shared import Inches, Pt, Cm

from docx.enum.style import WD_STYLE_TYPE
from docx.enum.section import WD_SECTION
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_BREAK, WD_BREAK_TYPE
from docx.enum.table import WD_ALIGN_VERTICAL, WD_ROW_HEIGHT
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_TABLE_DIRECTION
from docx.enum.style import WD_STYLE
from docx.oxml.shared import OxmlElement, qn


from django.shortcuts import render, redirect, get_list_or_404
from django.views import generic
from django.views.generic import TemplateView, ListView, CreateView
from django.contrib.messages.views import SuccessMessageMixin

from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest, JsonResponse, HttpResponseServerError

from datetime import datetime, date
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth import authenticate
from requests.api import get
from bases.views import SinPrivilegios
from bases.views import *
from .models import Departamento, Partes, Contratos, Doctos, Tipocontrato, Requisitos, Valida, Secuencia, Regimen, Ciclos, Puestos
from .forms import DepartamentoForm, PartesForm, ContratosForm, PuestosForm
from bases.views import SinPrivilegios
from django.core.files.storage import FileSystemStorage, get_storage_class
from api.serializer import TipocontratoSerializer


class VistaBaseCreate(SuccessMessageMixin, SinPrivilegios, generic.CreateView):
    context_object_name = 'obj'
    success_message = "Registro Agregado Satisfactoriamente"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class VistaBaseEdit(SuccessMessageMixin, SinPrivilegios, generic.UpdateView):
    context_object_name = 'obj'
    success_message = "Registro Actualizado Satisfactoriamente"

    def form_valid(self, form):
        #form.instance.um = self.request.user.id
        return super().form_valid(form)


class DepartamentoView(SinPrivilegios, generic.ListView):
    model = Departamento
    template_name = "cto/departamento_list.html"
    context_object_name = "obj"
    permission_required = "cto.view_departamento"


class DepartamentoNew(VistaBaseCreate):
    model = Departamento
    template_name = "cto/departamento_form.html"
    form_class = DepartamentoForm
    success_url = reverse_lazy("cto:departamento_list")
    permission_required = "cto.add_departamento"


class DepartamentoEdit(VistaBaseEdit):
    model = Departamento
    template_name = "cto/departamento_form.html"
    form_class = DepartamentoForm
    success_url = reverse_lazy("cto:departamento_list")
    permission_required = "cto.change_departamento"


@login_required(login_url="/login/")
@permission_required("cto.change_departamento", login_url="/login/")
def departamentoInactivar(request, id):
    departamento = Departamento.objects.filter(pk=id).first()

    if request.method == "POST":
        if departamento:
            departamento.estado = not departamento.estado
            departamento.save()
            return HttpResponse("OK")
        return HttpResponse("FAIL")

    return HttpResponse("FAIL")


class PartesView(SinPrivilegios, generic.ListView):
    model = Partes
    template_name = "cto/partes_list.html"
    context_object_name = "obj"
    success_url = reverse_lazy("cto:partes_list")
    permission_required = "cto.view_partes"

    def get_queryset(self):
        current_userx = self.request.user.id
        # print(current_userx)
        queryset = Partes.objects.filter(user_id=current_userx)
        xdepa = 2
        for part in queryset:
            xdepa = part.claveDepartamento_id

        # print(xdepa)

        querydep = Departamento.objects.all()
        # print(querydep)
        for depa in querydep:

            if depa.claveDepartamento == xdepa:
                # print(depa.claveDepartamento)
                xr1 = "0"+str(depa.rango1)
                xr2 = "0"+str(depa.rango2)
                # print(xdepa)
                # print(xr1)
                # print(xr2)
                return Partes.objects.filter(Q(claveDepartamento__gte=xr1),  Q(claveDepartamento__lte=xr2))
            # else:
            #    messages.ERROR (request, '¡Rango de Departamentos no registrado!')
            #    return HttpResponseRedirect('/admn/')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(PartesView, self).get_context_data(**kwargs)
        # Get the blog from id and add it to the context
        return context


class PartesNew(VistaBaseCreate):
    model = Partes
    template_name = "cto/partes_form.html"
    form_class = PartesForm
    success_url = reverse_lazy("cto:partes_list")
    permission_required = "cto.add_partes"


class PartesEdit(VistaBaseEdit):
    model = Partes
    template_name = "cto/partes_form.html"
    form_class = PartesForm
    success_url = reverse_lazy("cto:partes_list")
    permission_required = "cto.change_partes"


@login_required(login_url="/login/")
@permission_required("cto.change_partes", login_url="/login/")
def partesInactivar(request, id):
    partes = Partes.objects.filter(pk=id).first()

    if request.method == "POST":
        if partes:
            partes.estado = not partes.estado
            partes.save()
            return HttpResponse("OK")
        return HttpResponse("FAIL")

    return HttpResponse("FAIL")


class ContratosView(SinPrivilegios, generic.ListView):
    model = Contratos
    template_name = "cto/contrato_list.html"
    context_object_name = "obj"
    success_url = reverse_lazy("cto:contrato_list")
    permission_required = "cto.view_contratos"

    def get_queryset(self):
        xtipo = 0
        tipocontrato = Tipocontrato.objects.filter(marcatipoContrato=True)
        for x in tipocontrato:
            if x.marcatipoContrato == True:
                xtipo = x.id
                # print(xtipo)
        # r = requests.get('http://127.0.0.1:8000/api/v1/tipocontrato/7')
        # print (r.content)
        # print (r.status_code)
        # print (r.headers)
        # print (r.json)
        # x=urllib.request.urlretrieve('http://127.0.0.1:8000/api/v1/tipocontrato/7')
        # print(x)8

        current_userx = self.request.user.id
        #conditions = dict(current_user=current_userx, uc_id=self.request.user)
        #queryset = queryset.filter(**conditions)
        # return Contratos.objects.all()

        return Contratos.objects.filter(
            (Q(current_user=current_userx) | Q(uc_id=self.request.user)), Q(
                tipocontrato_id=xtipo)
        )
        # return SpyorEnc.objects.filter(
        #    Q(current_user=current_userx) | Q(uc_id=self.request.user) | Q(el_jefe=current_userx)
        # )

    def get_context_data(self, **kwargs):

        # Call the base implementation first to get a context
        context = super(ContratosView, self).get_context_data(**kwargs)
        # Get the blog from id and add it to the context
        context['some_data'] = Partes.objects.all()
        context['some_data2'] = Departamento.objects.all()
        context['some_data3'] = Tipocontrato.objects.filter(
            marcatipoContrato=True)
        return context


class ContratosView2(SinPrivilegios, generic.ListView):
    model = Contratos
    template_name = "cto/contrato_list.html"
    context_object_name = "obj"
    success_url = reverse_lazy("cto:contrato_list")
    permission_required = "cto.view_contratos"

    def get_queryset(self):
        xtipo = 0
        tipocontrato = Tipocontrato.objects.filter(marcatipoContrato=True)
        for x in tipocontrato:
            if x.marcatipoContrato == True:
                xtipo = x.id
                # print(xtipo)
        # r = requests.get('http://127.0.0.1:8000/api/v1/tipocontrato/7')
        # print (r.content)
        # print (r.status_code)
        # print (r.headers)
        # print (r.json)
        # x=urllib.request.urlretrieve('http://127.0.0.1:8000/api/v1/tipocontrato/7')
        # print(x)8

        current_userx = self.request.user.id
        #conditions = dict(current_user=current_userx, uc_id=self.request.user)
        #queryset = queryset.filter(**conditions)
        # return Contratos.objects.all()

        return Contratos.objects.filter(
            (Q(current_user=current_userx) | Q(uc_id=self.request.user)), Q(
                tipocontrato_id=xtipo)
        )
        # return SpyorEnc.objects.filter(
        #    Q(current_user=current_userx) | Q(uc_id=self.request.user) | Q(el_jefe=current_userx)
        # )

    def get_context_data(self, **kwargs):

        # Call the base implementation first to get a context
        context = super(ContratosView, self).get_context_data(**kwargs)
        # Get the blog from id and add it to the context
        context['some_data'] = Partes.objects.all()
        context['some_data2'] = Departamento.objects.all()
        context['some_data3'] = Tipocontrato.objects.filter(
            marcatipoContrato=True)
        return context


@login_required(login_url='/login/')
@permission_required('cto.add_contratos', login_url='bases:sin_privilegios')
def contratos2(request, contrato_id=None):

    template_name = 'cto/contrato.html'
    detalle = {}
    #secuencia_data = {}
    #xUsuario = (request.user.id)
    # print(xUsuario)
    #print (contrato_id)

    if contrato_id:

cto/templates/cto/contrato_list.html
{% extends 'base/base.html' %}
{% load static %}
{% load formatags %}
 
{% block top_bar %}
      {% for x in some_data3 %} 
         {% if x.marcatipoContrato  %} 
            <h5 class="m-20 font-weight-bolder text-success badge-light">{{ x.tipoContrato }}   </h5>
         {% endif %}
      {% endfor %}        
      <p class="m-0 font-weight-bold text-primary">  user: {{ user.username }} &nbsp;&nbsp; {{ user.last_name }} {{ user.first_name }} </p>
    
    {% for x in some_data %}
      
      {% if x.user_id == user.id %}
     
         <span class="m-0 font-weight-bold text-primary">  Depto: &nbsp;&nbsp; {{ x.claveDepartamento }}</span>
        
      {% endif %}                      
    {% endfor %} 
   
    
 
 {% endblock top_bar %}




{% block page_content %}
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
   
      {% for item in obj %}
        
        {% for x in some_data %}
           {% if x.user_id == item.astep1 %}
              <a class="btn btn-secondary" href="{% url 'cto:departamento_list' %}"><i cass="far fa-calendar-plus"></i>REV {{x.usuario}}</a>
           {% endif %}                      
        {% endfor %} 
               
      {% endfor %} 


      <!-- <div class="dropdown no-arrow">
      <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
        <div class="dropdown-header">Acciones:</div>
        <a class="dropdown-item" onclick="return abrir_modal('{% url 'cto:departamento_list' %}')" href="#"><i class="far fa-calendar-plus"></i> Nuevo</a>
      </div>
    </div> -->
  </div>
  <!-- Card Body -->
  <div class="card-body">
    {% if not obj %}
    <div class="alert alert-info">No Hay Contratos</div>
    {% endif %}
    <div class="buttons-toolbar">
        <a class="btn btn-danger" href="{% url 'cto:contrato_new' %}"><i cass="far fa-calendar-plus"></i>Nuevo Contrato</a>
        
    </div>


    <table 
       id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-MX"
      
    >
    <thead>
      <th data-sortable="true" data-field="id">Folio&nbsp;&nbsp;</th>
      <th data-sortable="true" data-field="tipocontrato">Tipo de Contrato</th>
      <th data-sortable="true" data-field="status">Status&nbsp;&nbsp;</th>        
      
      <th data-sortable="true" data-field="datecontrato">Fecha</th>
      <th data-sortable="true" data-field="parte2">Sujeto del contrato</th>
      <th data-sortable="true" data-field="importeContrato">Importe</th>
      
      <th class="all">Contrato</th>
      
       
        <th class="all">Modificar</th> 
      
    </thead>
   
   <tbody>
      {% for item in obj %}
         

      <tr>
        <td>{{ item.id}}</td>
        
        
        <td>{{ item.tipocontrato }}</td>
        <td>{{ item.status }}</td>
        <td>{{ item.datecontrato|date:'d-M-Y' }}</td>
        <td>{{ item.parte2 }}</td>
        <td>{{ item.importeContrato }}</td>
        <td>
          <a href="{% url 'cto:contrato_edit' item.id %}" class="href btn btn-success btn-circle">
              <i class="far fa-edit"></i>
          </a>
        </td>
        <td>
             {% if item.status == "CAP" %}
                <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'cto:contrato_edit2' item.id %}')"><i class="far fa-edit"></i></button>
              {% endif %}
        </td> 
      </tr>
      {% endfor %}
    </tbody>

    </table>
  </div>
</div>
{% endblock %}
{% block js_page %}
<script>

</script>
{% endblock %}

cto/templates/cto/contrato_list2.html
{% extends 'base/base.html' %}
{% load static %}
{% load formatags %}
 
{% block top_bar %}
      {% for x in some_data3 %} 
         {% if x.marcatipoContrato  %} 
            <h6 class="m-0 font-weight-bold text-primary">{{ x.tipoContrato }}   </h6>
         {% endif %}
      {% endfor %}        
      <p class="m-0 font-weight-bold text-primary">  user: {{ user.username }} &nbsp;&nbsp; {{ user.last_name }} {{ user.first_name }} </p>
    
    {% for x in some_data %}
      
      {% if x.user_id == user.id %}
     
         <span class="m-0 font-weight-bold text-primary">  Depto: &nbsp;&nbsp; {{ x.claveDepartamento }}</span>
        
      {% endif %}                      
    {% endfor %} 
   
    
 
 {% endblock top_bar %}




{% block page_content %}
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
   
      {% for item in obj %}
        
        {% for x in some_data %}
           {% if x.user_id == item.astep1 %}
              <a class="btn btn-secondary" href="{% url 'cto:departamento_list' %}"><i cass="far fa-calendar-plus"></i>REV {{x.usuario}}</a>
           {% endif %}                      
        {% endfor %} 
               
      {% endfor %} 


      <!-- <div class="dropdown no-arrow">
      <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
        <div class="dropdown-header">Acciones:</div>
        <a class="dropdown-item" onclick="return abrir_modal('{% url 'cto:departamento_list' %}')" href="#"><i class="far fa-calendar-plus"></i> Nuevo</a>
      </div>
    </div> -->
  </div>
  <!-- Card Body -->
  <div class="card-body">
    {% if not obj %}
    <div class="alert alert-info">No Hay Contratos</div>
    {% endif %}
    <div class="buttons-toolbar">
        <a class="btn btn-primary" href="{% url 'cto:contrato_new' %}"><i cass="far fa-calendar-plus"></i>Nuevo Contrato</a>
        
    </div>


    <table 
       id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-MX"
      
    >
    <thead>
      <th data-sortable="true" data-field="id">Folio&nbsp;&nbsp;</th>
      <th data-sortable="true" data-field="tipocontrato">Tipo de Contrato</th>
      <th data-sortable="true" data-field="status">Status&nbsp;&nbsp;</th>        
      
      <th data-sortable="true" data-field="datecontrato">Fecha</th>
      <th data-sortable="true" data-field="parte2">Sujeto del contrato</th>
      <th data-sortable="true" data-field="importeContrato">Importe</th>
      
      <th class="all">Contrato</th>
      
       
        <th class="all">Modificar</th> 
      
    </thead>
   
   <tbody>
      {% for item in obj %}
         

      <tr>
        <td>{{ item.id}}</td>
        
        
        <td>{{ item.tipocontrato }}</td>
        <td>{{ item.status }}</td>
        <td>{{ item.datecontrato|date:'d-M-Y' }}</td>
        <td>{{ item.parte2 }}</td>
        <td>{{ item.importeContrato }}</td>
        <td>
          <a href="{% url 'cto:contrato_edit' item.id %}" class="href btn btn-success btn-circle">
              <i class="far fa-edit"></i>
          </a>
        </td>
        <td>
             {% if item.status == "CAP" %}
                <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'cto:contrato_edit2' item.id %}')"><i class="far fa-edit"></i></button>
              {% endif %}
        </td> 
      </tr>
      {% endfor %}
    </tbody>

    </table>
  </div>
</div>
{% endblock %}
{% block js_page %}
<script>

</script>
{% endblock %}

cto/templates/cto/departamento_form.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if obj %}
        <form role="form" action="{% url 'cto:departamento_edit' obj.pk %}" method="post"  class="form-inline">
        {% else %}
        <form role="form" action="{% url 'cto:departamento_new' %}" method="post"  class="form-inline">
        {% endif %}
            <div class="col-xl-12 col-md-12 mb-12">
                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            {% if obj %} Editar {% else %} Nuevo {% endif %} Departamento
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            {{ form.as_p }}
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                        Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div> 

cto/templates/cto/departamento_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Departamentos</h6>
    <div class="dropdown no-arrow">
      <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
        <div class="dropdown-header">Acciones:</div>
        <a class="dropdown-item" onclick="return abrir_modal('{% url 'cto:departamento_new' %}')" href="#"><i class="far fa-calendar-plus"></i> Nuevo</a>
      </div>
    </div>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    {% if not obj %}
    <div class="alert alert-info">No Hay Departamentos</div>
    {% endif %}
    <div class="buttons-toolbar">
        <a class="dropdown-item" onclick="return abrir_modal('{% url 'cto:departamento_new' %}')" href="#"><i class="far fa-calendar-plus"></i> Nuevo</a>
    </div>

    <table 
      id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-MX"
    >
      <thead>
          <th data-sortable="true" data-field="claveDepartamento">Clave</th>
          <th data-sortable="true" data-field="nombreDepartamento">Departamento</th>
          <th data-field="estado">Estado</th>
          <th class="all">Acciones</th>  
      </thead>
      <tbody>
        {% for item in obj%}
        <tr>
          <td>{{ item.claveDepartamento }}</td>
          <td>{{ item.nombreDepartamento }}</td>
          <td >{#item.estado|yesno:"Activo,Inactivo"#}
            <div onclick="inactivar({{item.id}})">
                {% if item.estado %}
                <i class="far fa-thumbs-up text-primary"></i>
              {% else %}
                <i class="far fa-thumbs-down text-danger"></i>
              {% endif %}
            </div>
          </td>
          <td>
            <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'cto:departamento_edit' item.id %}')"><i class="far fa-edit"></i></button>
          </td>
        </tr>
        {% endfor %}
      </tbody>

    </table>
  </div>
</div>
{% endblock %}
{% block js_page %}
<script>
  function inactivar(id)
  {
    var data = {id:id};
    data = JSON.stringify(data);
    var token = '{{csrf_token}}';
    // alert(token);
    // alert(id);
    
    $.ajax({
      headers : {"X-CSRFToken": token},
      type:"POST",
      url:"/cat/departamentos/estado/"+id,
      data: data,
      success: function(response){
        if(response==="OK")
        {
          location.reload(true);
        }
        else{
          mensaje("Error Intentado Cambiar Estado a Departamento");
        }
      },
      error: function(jqXHR, textStatus, errorThrow){
        console.log(textStatus, errorThrow);
        mensaje(errorThrow,'red');
        cerrar_modal();
      }
    });
  }
// Call the dataTables jQuery plugin
// $(document).ready(function() {
//   $('.table').DataTable();
// });
</script>
{% endblock %}

cto/templates/cto/messages.html
        {% if messages %}
            {% for message in messages %}
                <div class="alert {{ message.tags }} m-2" id="msg" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %} 